### PR TITLE
Unneccesary files removed

### LINKED ISSUE #10: Remove the unused files from the project
**Actual Behaviour**

Many unused HTML/CSS/JS files or CDN links are presents in the project.

**Expected Behaviour**

Remove the unused files/links from the project

**Would you like to work on the issue?**

Anyone can claim the issue :) Feel free to comment.

### PR DESCRIPTION
**Pull request by LalitSharma7**
- [ x] Included a Preview link and screenshot showing after and before the changes.
- [x ] Included a description of the change below.
- [ x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #10

## Description / Changes

@jogendra help me i am unable to figure out which files are still there which needs to be removed

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by LalitSharma7** [comment]
@jogendra please help me where i am lacking

**Comment by jogendra** [comment]
@Rattlecode17sh I think **[landing-page](https://github.com/jogendra/HealthLedger/tree/master/landing-page)** directory is not being used. check and remove.

**Comment by LalitSharma7** [comment]
@jogendra done

**Comment by jogendra** [comment]
@Rattlecode17sh Please provide the preview link!

**Comment by LalitSharma7** [comment]
https://rattlecode17sh.github.io/HealthLedger/

**Comment by LalitSharma7** [comment]
@jogendra please review

**Review by jogendra — APPROVED** [review]

**Pull request merged**
