### PR TITLE
Remove the unused files from the project

### LINKED ISSUE #10: Remove the unused files from the project
**Actual Behaviour**

Many unused HTML/CSS/JS files or CDN links are presents in the project.

**Expected Behaviour**

Remove the unused files/links from the project

**Would you like to work on the issue?**

Anyone can claim the issue :) Feel free to comment.

### PR DESCRIPTION
**Pull request by LalitSharma7**
- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #10 

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by LalitSharma7** [comment]
Here is the live link

https://rattlecode17sh.github.io/HealthLedger/

**Comment by LalitSharma7** [comment]
@jogendra please check it

**Review by jogendra — CHANGES_REQUESTED** [review]
I think all the unused files are not removed. Please check carefully and remove all the unused files.

**Comment by jogendra** [comment]
@Rattlecode17sh Hey are you still working on it?

**Pull request closed without merging**
