### PR TITLE
Imporve navbar on pages except homepage fixed #14

### LINKED ISSUE #14: Improve navbar on pages except homepage
**Actual Behaviour**

Navbar on the pages os not well designed

**Expected Behaviour**

Improve the UI/UX of navbar on all the pages except homepage

**Would you like to work on the issue?**

Anyone can claim this issue. feel free to drop a comment.

### PR DESCRIPTION
**Pull request by anupm12**
- [x] Included a Preview link and screenshot showing after and before the changes.
- [x] Included a description of the change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- [Preview Link](url)

- Fixes #<Issue Number>

## Description / Changes
Changes done are-
1. Made navbar fixed on a scroll
2. Rearranged the items in the navbar
3. Added required margin and padding to make all navbar elements to look more clear

Live link https://healthledger-navbar.netlify.com/

### After:

- - - - - - - - - - - -

### CODE REVIEW

**Comment by anupm12** [comment]
Live link https://healthledger-navbar.netlify.com/

**Review by jogendra — CHANGES_REQUESTED** [review]
- Keep the title of the page in the center
- Home button should be first link in
- After home, put all the links available on the main page

**Comment by anupm12** [comment]
@jogendra I have made the changes.

**Review by jogendra — APPROVED** [review]
Perfect!

**Pull request merged**
